version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8082:82"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    build:
      context: ./db
    ports:
      - "27017:27017"
